CaptureThePortal:
    dieorbounce: false
    enablebouncing: true
    delay: 6
    cooldown: 120
    rewardaftercooldown: 0
    cooldown_message_timeleft: 20
    cooldown_message_timeleft_increments: 0
    fullgroupnames: false
    enablekickfromworld: true
    usenations: false
    persistcapture: true
    allow_neutral_to_portal: false
    enablenethersupport: true
    enableEndersupport: false
    enablewormholesupport: false
    enablestargatesupport: false
    enableMVPortals: false
    enablepermissionssupport: true
    enablefactionsupport: false
    enabletownysupport: false
    enablesimpleclanssupport: false
    enablesimpleclans2support: false
    enablegodssupport: false
    messages:
      capture_message: '[team] [group] is attempting to capture the [type].'
      cooldown_message: 'The portal will be available for capture again within [cooldown].'
      available_message: 'The portal at [location] is now ready to be captured!'
      reward_message: '[team] [group] has been rewarded [reward]!'
      player_portal_is_cooldown: 'This Portal is on Cooldown, total cooldown time is [cooldown]'
      player_someone_else_capturing: 'Someone else is currently capturing this portal!'
      player_capturing_portal_holdit: 'Capturing Portal! Hold it for [capturetime] to capture it!'
      player_not_allowed_to_use: 'Your team has not captured this portal yet so, you are not allowed to use it!'
      player_not_allowed_die_use: 'Your body was ripped apart while trying to cross the portal. The portal does not belong to your faction.'
      player_forced_respawn: 'Another team captured the portal! You are now forced to respawn!'
      player_captured_it: 'Succesfully captured the portal!'
      player_failed_capture: 'Failed to capture the Portal because you moved.'
      player_not_allowed_to_use_neutral: 'You are not allowed to use this Portal because you are not part of a team!'
