name: CaptureThePortal
main: org.wargamer2010.capturetheportal.CaptureThePortal
version: 2.2.0
dev-url: http://dev.bukkit.org/server-mods/capturetheportal
author: Wargamer2010
softdepend: [Vault, Multiverse-Core, PermissionsEx, SimpleClans, SimpleClans2, Towny, Gods, Factions]
description: "Capture the Portal by holding the wool square"
commands:
  capturetheportal:
    description: Admin commands for CaptureThePortal
    usage: /capturetheportal [reload|info]
  ctp:
    description: Admin commands for CaptureThePortal
    usage: /ctp [reload|info]
